#!/usr/bin/env python3

hard= {"key1": [1, 2], "key2": [3, 4], "key3": [5, 6]}  
print(hard{get.value("key3"})
 
harder= [{"key1": [1, 2], "key2": [3, 4], "key3": [5, 6]}] 

 
hardest= {"thisishard":[{"key1": [1, 2], "key2": [3, 4], "key3": [5, 6]}]} 

